function card()
            {
                var r=document.getElementById("container_1");
                r.classList.replace("container1","container1s");
                var r=document.getElementById("container_2");
                r.classList.replace("container2","container2s");
                var r=document.getElementById("container_f");
                r.classList.replace("containerf","containers");
                var r=document.getElementById("buttons");
                r.classList.replace("b","bs");
                var r=document.getElementById("ima");
                r.classList.replace("image","images");
                var r=document.getElementById("ima2");
                r.classList.replace("image2","image2s");
                var r=document.getElementById("box_2");
                r.classList.replace("box2","box2s");
                var r=document.getElementById("box_4");
                r.classList.replace("box4","box4s");
                var r=document.getElementById("l_1");
                r.classList.replace("l1","l1s");
                var r=document.getElementById("l_2");
                r.classList.replace("l2","l2s");
                var r=document.getElementById("l_3");
                r.classList.replace("l_3","l3s");
                var r=document.getElementById("l_4");
                r.classList.replace("l4","l4s");
                var r=document.getElementById("remote");
                r.classList.replace("b1","b1s");
                var r=document.getElementById("sketch");
                r.classList.replace("b2","b2s");
                var r=document.getElementById("b_3");
                r.classList.replace("b3","b3s");
                var r=document.getElementById("p_rice");
                r.classList.replace("price","prices");
                var r=document.getElementById("p_1");
                r.classList.replace("p1","p1s");
                var r=document.getElementById("p_2");
                r.classList.replace("p2","p2s");
                var r=document.getElementById("p_3");
                r.classList.replace("p3","p3s");
                var r=document.getElementById("p_4");
                r.classList.replace("p4","p4s");
                var r=document.getElementById("a_1");
                r.classList.replace("a1","a1s");
                var r=document.getElementById("a_2");
                r.classList.replace("a2","a2s");
                var r=document.getElementById("a_1f");
                r.classList.replace("a1f","a1fs");
                var r=document.getElementById("a_2f");
                r.classList.replace("a2f","a2fs");
                var r=document.getElementById("a_pply");
                r.classList.replace("apply","applys");
                var r=document.getElementById("apply_f");
                r.classList.replace("applyf","applyfs");
                var r=document.getElementById("price_1");
                r.classList.replace("price1","price1s");
                var r=document.getElementById("button1");
                r.classList.replace("but1","but1s");
                var r=document.getElementById("button2");
                r.classList.replace("but2","but2s");
                
            }
            function detailed()
            {
                var r=document.getElementById("container_1");
                r.classList.replace("container1s","container1");
                var r=document.getElementById("container_2");
                r.classList.replace("container2s","container2");
                var r=document.getElementById("container_f");
                r.classList.replace("containers","containerf");
                var r=document.getElementById("buttons");
                r.classList.replace("bs","b");
                var r=document.getElementById("ima");
                r.classList.replace("images","image");
                var r=document.getElementById("ima2");
                r.classList.replace("image2s","image2");
                var r=document.getElementById("box_2");
                r.classList.replace("box2s","box2");
                var r=document.getElementById("box_4");
                r.classList.replace("box4s","box4");
                var r=document.getElementById("l_1");
                r.classList.replace("l1s","l1");
                var r=document.getElementById("l_2");
                r.classList.replace("l2s","l2");
                var r=document.getElementById("l_3");
                r.classList.replace("l3s","l_3");
                var r=document.getElementById("l_4");
                r.classList.replace("l4s","l4");
                var r=document.getElementById("remote");
                r.classList.replace("b1s","b1");
                var r=document.getElementById("sketch");
                r.classList.replace("b2s","b2");
                var r=document.getElementById("b_3");
                r.classList.replace("b3s","b3");
                var r=document.getElementById("p_rice");
                r.classList.replace("prices","price");
                var r=document.getElementById("p_1");
                r.classList.replace("p1s","p1");
                var r=document.getElementById("p_2");
                r.classList.replace("p2s","p2");
                var r=document.getElementById("p_3");
                r.classList.replace("p3s","p3");
                var r=document.getElementById("p_4");
                r.classList.replace("p4s","p4");
                var r=document.getElementById("a_1");
                r.classList.replace("a1s","a1");
                var r=document.getElementById("a_2");
                r.classList.replace("a2s","a2");
                var r=document.getElementById("a_1f");
                r.classList.replace("a1fs","a1f");
                var r=document.getElementById("a_2f");
                r.classList.replace("a2fs","a2f");
                var r=document.getElementById("a_pply");
                r.classList.replace("applys","apply");
                var r=document.getElementById("apply_f");
                r.classList.replace("applyfs","applyf");
                var r=document.getElementById("price_1");
                r.classList.replace("price1s","price1");
                var r=document.getElementById("button1");
                r.classList.replace("but1s","but1");
                var r=document.getElementById("button2");
                r.classList.replace("but2s","but2");
                
            }